python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.1__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.1__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.1__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.1__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.1__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;

python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.25__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.25__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.25__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.25__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.25__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;

python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.5__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.5__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.5__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.5__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.5__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;


python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.75__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.75__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.75__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.75__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.75__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;


python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.9__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.9__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.9__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.9__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.9__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;


python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.99__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.99__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.99__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.99__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_0.99__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;


python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_1.0__seed_5/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_1.0__seed_6/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_1.0__seed_7/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_1.0__seed_8/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;
python count_evs.py --input_path prototype_results/ucf101/train_2__test_3__tail_10__cover_1.0__seed_9/0/phase_4_incremental_ti3d_incremental_evm_tail_0.2_online/9/;

